[build-system]
requires = ["setuptools>=61.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
known_third_party = ["sqlmodel", "sqlmodel_learning"]
